# site settings
title: BIG? NOT YET
subtitle: DISCOVER NEW ARTISTS
email: HELLO@BIGNOTYET.COM
description: A new way to discover emerging artists. <br /> Are you ready for this adventure?
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
permalink: /:categories/:title

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/bignotyet
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed